config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :dashboards, only: [:index]
    resources :items
    resources :orders do
      member do
        get "paid_order"
        get "complete_order"
        get "cancel_order"
      end
    end
    resources :categories do
      member do
        post "remove_item"
      end
    end
  end
  resources :items, only: [:index]
  resource :cart, only: [:show]
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
  resources :categories, only: [:show]
  resources :orders, only: [:index]
  get 'order_confirmation', to: 'orders#order_confirmation'
  resources :cart_items, only: [:create, :destroy, :update] do
    collection do
      get 'checkout'
    end
  end
  root 'items#index'
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :order_items
  has_many :orders, through: :order_items
  has_and_belongs_to_many :categories
  has_many :cart_items
  has_many :carts, through: :cart_items
  has_one_attached :image



  validates :title, presence: true, uniqueness: true
  validates :description, presence: true
  validates :price, numericality: { greater_than: 0 }
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
    before_action :authorize_admin
    def index
        @items = Item.all
    end

    def new
        @item = Item.new
    end

    def edit
        @item = Item.find(params[:id])
    end

   def update
    @item = Item.find(params[:id])
       if @item.update(item_params)
        redirect_to admin_items_path, notice: 'Item was successfully updated.'
      else
        render :edit
      end
   end
   


    def create
        @item = Item.new(item_params)
        if @item.save
          flash[:success] = "Item successfully Added"
          redirect_to  admin_items_path
        else
          flash[:error] = "Something went wrong"
          render 'new'
        end
    end

    def destroy
        @item = Item.find(params[:id])
        @item.destroy
        redirect_to admin_items_path
    end
    
    private

    def item_params
        params.require(:item).permit(:title, :description, :price,:quantity,:category_ids,:image)
    end
    
    
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    if params[:search]
      @item = Item.where("LOWER(title) LIKE ?", "%#{params[(:search)].downcase}%")
    elsif params[:category_id]
      @category = Category.find(params[:category_id])
      @item =  @category.items
    else
      @item = Item.all
    end
  end
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/admin/items/edit.html.erb
<!DOCTYPE html>
<html>
<head>
    <%= stylesheet_link_tag 'items', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>
<body>
<div class="Box-container">
    <div class="row">
        <%= render "layouts/flash_message" %>
        <div class="Bx">
            <h2><b>Modify Item</b></h2>
            <%= form_with(model: [:admin, @item], url: admin_item_path(@item), method: :patch, local: true) do |form| %>
                <div class="form-group">
                    <%= form.label :title %>
                </div>
                <%= form.text_field :title, class:"field" %>

                <div class="form-group">
                    <%= form.label :description %>
                </div>
                <%= form.text_area :description, class:"field" %>

                <div class="form-group">
                    <%= form.label :quantity %>
                </div>
                <%= form.number_field :quantity, step: 1, class:"field" %>

                <div class="form-group">
                    <%= form.label :price %>
                </div>
                <%= form.number_field :price, step: 1, class:"field" %>

                <div class="form-group">
                    <%= form.label :image %>
                </div>  
                    <%= form.file_field :image %>

                <div class="form-group">
                    <%= form.label :category %>
                </div>  
                <%= form.collection_select :category_ids, Category.all, :id, :name, include_blank: true %> <br><br>

                    <%= form.submit "Submit", class:"Submit-button" %>
            <% end %>
        </div>
    </div>
</div>

</body>
</html>

app/views/admin/items/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <%= stylesheet_link_tag 'items', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>
<body>
<div class="Box-container">
  <div class="row">
    <%= render "layouts/flash_message" %>
    <table class="table1">
      <thead>
        <tr>
          <th class="n">Title</th>
          <th class="n">Description</th>
          <th class="n">Quantity</th>
          <th class="n">Price</th>
          <th class="bu"><%= link_to new_admin_item_path, class: "btn btn-primary" do %><i class="fas fa-plus"></i><% end %></th>
        </tr>
      </thead>
      <% @items.each do |item| %>
      <tbody>
        <tr>
          <td><%= item.title %></td>
          <td><%= item.description %></td>
          <td><%= item.quantity %></td>
          <td><%= item.price %></td>
          <td>
            <%= button_to admin_item_path(item), method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure?' } do %><i class="fas fa-trash-alt"></i><% end %><br>
            <%= link_to edit_admin_item_path(item), class: "btn btn-dark " do %><i class="fas fa-edit"></i><% end %>
          </td>
        </tr>
      </tbody>
      <% end %>
    </table>
  </div>
</div>
</body>
</html>

app/views/admin/items/new.html.erb
<!DOCTYPE html>
<html>
<head>
    <%= stylesheet_link_tag 'items', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>
<body>
<div class="Box-container">
    <div class="row">
      <div class="Bx">
          <h2><b>Add Item</b></h2>
          <%= form_with(model: [:admin, @item], url: admin_items_path, method: :post, local: true) do |form| %>
            <div class="form-group">
              <%= form.label :title %>
            </div>
              <%= form.text_field :title, class: "field" %>
            
            <div class="form-group">
              <%= form.label :description %>
            </div>
              <%= form.text_area :description, class: "field" %>
            
            <div class="form-group">
              <%= form.label :quantity %>
            </div>
              <%= form.number_field :quantity, step: 1, class: "field" %>
            
            <div class="form-group">
              <%= form.label :price %>
            </div>
              <%= form.number_field :price, step: 1, class: "field" %>
            
            <div class="form-group">
              <%= form.label :image %>
            </div>
              <%= form.file_field :image, class: "field" %>
            
            <div class="form-group">
              <%= form.label :category %>
            </div>
              <%= form.collection_select :category_ids, Category.all, :id, :name, include_blank: true, class: "field" %>
            
            <%= form.submit "Submit", class: "Submit-button" %>
          <% end %>
      </div>
    </div>
  </div>
</body>
</html>