config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :dashboards, only: [:index]
    resources :items
    resources :orders do
      member do
        get "paid_order"
        get "complete_order"
        get "cancel_order"
      end
    end
    resources :categories do
      member do
        post "remove_item"
      end
    end
  end
  resources :items, only: [:index]
  resource :cart, only: [:show]
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
  resources :categories, only: [:show]
  resources :orders, only: [:index]
  get 'order_confirmation', to: 'orders#order_confirmation'
  resources :cart_items, only: [:create, :destroy, :update] do
    collection do
      get 'checkout'
    end
  end
  root 'items#index'
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items
  has_many :items, through: :order_items

  validates :user, presence: true
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
    def index
        @status = Order.pluck(:status).uniq
        if params[:status].present?
            @orders = Order.where(status: params[:status])
          else
            @orders = Order.all
          end
    end

    def show
        @order = Order.find(params[:id])
        @order_items = @order.order_items.includes(:item)
        @user = @order.user
    end

    def paid_order
        @order = Order.find(params[:id])
        @order.update_attribute(:status,"paid")
        @order.update_attribute(:completed_at, Time.current)
        redirect_to admin_orders_path
    end

    def complete_order
        @order = Order.find(params[:id]) 
        @order.update_attribute(:status,"completed")
        @order.update_attribute(:completed_at, Time.current)
        redirect_to admin_orders_path
    end

    def cancel_order
        @order = Order.find(params[:id]) 
        @order.update_attribute(:status,"canceled")
        @order.update_attribute(:canceled_at, Time.current)
        redirect_to admin_orders_path
    end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :custom_authenticate_user!
  def index
    @orders = current_user.orders
  end

  def order_confirmation
  end

end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/orders/index.html.erb
<!DOCTYPE html>
<html lang = "en">
<head>
 <%= stylesheet_link_tag 'items', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>
<body>
<div class="B-container">
    <div class="row">
        <%= render "layouts/flash_message" %>
        <div class = "t-box">
            <table class="table1">
                <thead>
                    <tr>
                        <th class="n">Order ID</th>
                        <th class="n">Status</th>
                        <th class="n">Order Detail</th>
                        <th class="n">
                        <a class="bu dropdown-toggle" role="button" data-toggle="dropdown">Filtered Status</a>
                        <div class="dropdown-menu table table-hover">
                            <% @status.each do |s| %>
                            <%= link_to s, admin_orders_path(status: s), class: 'dropdown-item' %>
                            <% end %>
                        </div>
                        </th>
                    </tr>
                </thead>
                <% @orders.each do |order| %>
                <tbody>
                    <tr>
                        <td><%= order.id %></td>
                        <td><%= order.status %></td>
                        <td><%= link_to "Order Detail",admin_order_path(order),class:"btn btn-outline-primary" %></td>
                        <td>
                        <% if order.status == "ordered" %>
                            <%= link_to "Mark as paid",paid_order_admin_order_path(order), class:"btn btn-success cancel" %><br><br>
                            <%= link_to "Cancel",cancel_order_admin_order_path(order), class:"btn btn-danger cancel" %>
                        <% elsif order.status == "paid" %>
                            <%= link_to "Mark as Completed",complete_order_admin_order_path(order), class:"btn btn-success" %><br><br>
                            <%= link_to "Cancel",cancel_order_admin_order_path(order), class:"btn btn-danger cancel" %>
                        <% end %>
                        </td>
                    </tr>
                </tbody>
                <% end %>
            </table>
        </div>
    </div>
</div>                    
</body>
</html>

app/views/admin/orders/show.html.erb
<!DOCTYPE html>
<html lang = "en">
<head>
 <%= stylesheet_link_tag 'items', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>
<body>
<div class="Box-container">
    <div class="row">
        <%= render "layouts/flash_message" %>
        <table class="table1"> 
            <%= link_to "",admin_orders_path, class:"A bi bi-arrow-left" %>
            <thead>
                <tr>
                    <th class="n">Item</th>
                    <th class="n">Quantity</th>
                    <th class="n">Amount</th>
                    <th class="n">Purchaser Name</th>
                    <th class="n">Purchaser Email</th>
                </tr>
            </thead>
            <% total_price = 0 %>
            <% @order_items.each do |order| %>
             <tbody>
                <tr>
                    <td><%=image_tag "Food.jpeg", class:"i"%>  <B><%= order.item.title %></B></td>
                    <td><%= order.quantity %></td>
                    <td><%= order.amount%></td>
                    <td><%= @user.full_name %></td>
                    <td><%= @user.email %></td>
                    <% total_price += order.quantity * order.item.price %>
                </tr>
                <% end %>
                <tr>
                    <td colspan="3">
                            <div class="order-details">
                                <b>Total Price:</b> $<%= total_price %><br>
                                <b>Status:</b> <%= @order.status %><br>
                            </div>
                        </td>
                </tr>
             </tbody>
        </table>
    </div>
</div>                    
</body>
</html>