config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :dashboards, only: [:index]
    resources :items
    resources :orders do
      member do
        get "paid_order"
        get "complete_order"
        get "cancel_order"
      end
    end
    resources :categories do
      member do
        post "remove_item"
      end
    end
  end
  resources :items, only: [:index]
  resource :cart, only: [:show]
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
  resources :categories, only: [:show]
  resources :orders, only: [:index]
  get 'order_confirmation', to: 'orders#order_confirmation'
  resources :cart_items, only: [:create, :destroy, :update] do
    collection do
      get 'checkout'
    end
  end
  root 'items#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items
  has_many :items, through: :cart_items

  def merge_session_cart(session_cart)
    session_cart.each do |item|
      cart_item = cart_items.find_or_initialize_by(item_id: item['item_id'])
      cart_item.quantity ||= 0
      cart_item.quantity += item['quantity'].to_i
      cart_item.save
    end
  end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :cart
end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :items
  has_one_attached :image
  validates :name, presence: true, uniqueness: true
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :order_items
  has_many :orders, through: :order_items
  has_and_belongs_to_many :categories
  has_many :cart_items
  has_many :carts, through: :cart_items
  has_one_attached :image



  validates :title, presence: true, uniqueness: true
  validates :description, presence: true
  validates :price, numericality: { greater_than: 0 }
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items
  has_many :items, through: :order_items

  validates :user, presence: true
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :item

  validates :quantity, numericality: { greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  has_one :cart, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,:confirmable
  has_many :orders
  has_many :order_items, through: :orders
       
  validates :email, presence: true
  validates :full_name, presence: true
  validates :display_name, length: { in: 2..32 }

  def admin?
    role == 'admin'
  end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: :update

  def create
    if user_signed_in?
      @cart = current_user.cart || current_user.create_cart
      @cart_item = @cart.cart_items.find_or_initialize_by(item_id: cart_item_params[:item_id])
      @cart_item.quantity ||= 0
      requested_quantity = @cart_item.quantity + cart_item_params[:quantity].to_i
      item = Item.find(cart_item_params[:item_id])

      if requested_quantity > item.quantity
        redirect_back fallback_location: items_path, alert: "Unsufficient Quantity, Available quantity for this item is #{item.quantity}" 
      elsif @cart_item.update(quantity: requested_quantity)
        redirect_back fallback_location: items_path, notice: 'Item added to cart successfully.'
      else
        redirect_back fallback_location: root_path, alert: 'Failed to add item to cart.'
      end
    else
      add_to_session_cart
    end
  end

  def destroy
    if user_signed_in?
      @cart_item = CartItem.find(params[:id])
      @cart_item.destroy
      redirect_to cart_path, notice: 'Item removed from cart successfully.'
    else
      remove_from_session_cart
    end
  end

  def checkout
    if user_signed_in?
      @order = current_user.orders.create(
        amount: calculate_total_price,
        status: 'ordered',
        created_at: Time.current
      )
  
      current_user.cart.cart_items.each do |cart_item|
        @order.order_items.create(
          item: cart_item.item,
          quantity: cart_item.quantity,
          amount: cart_item.quantity * cart_item.item.price
        )
      end
  
      current_user.cart.cart_items.destroy_all
      redirect_to order_confirmation_path, notice: 'Your order has been placed successfully.'
    else
      redirect_to new_user_session_path, alert: "You need to sign in first."
    end
  end
  

  def update
    cart_item = CartItem.find(params[:id])
    item = Item.find(cart_item.item_id)
    new_quantity = params[:cart_item][:quantity].to_i

    if new_quantity > item.quantity
      redirect_back fallback_location: cart_path, alert: "Unsufficient Quantity, Available quantity for this item is #{item.quantity}"
    elsif cart_item.update(quantity: new_quantity)
      redirect_to cart_path, notice: 'Cart item updated successfully.'
    else
      redirect_back fallback_location: cart_path, alert: 'Failed to update cart item.'
    end
  end
    
  private
  
  def cart_item_params
    params.require(:cart_item).permit(:item_id, :quantity)
  end

  def add_to_session_cart
    session[:cart] ||= []
    item = session[:cart].find { |i| i['item_id'] == cart_item_params[:item_id].to_i }
    item_record = Item.find(cart_item_params[:item_id])

    if item
      new_quantity = item['quantity'] + cart_item_params[:quantity].to_i
      if new_quantity > item_record.quantity
        redirect_back fallback_location: items_path, alert: "Unsufficient Quantity, Available quantity for this item is #{item_record.quantity}" 
      else
        item['quantity'] += cart_item_params[:quantity].to_i
        redirect_back fallback_location: items_path, notice: 'Item added to cart successfully.'
      end
    else
      if cart_item_params[:quantity].to_i > item_record.quantity
        redirect_back fallback_location: items_path, alert: "Unsufficient Quantity, Available quantity for this item is #{item_record.quantity}" 
      else
        session[:cart] << cart_item_params.to_h
        redirect_back fallback_location: items_path, notice: 'Item added to cart successfully.'
      end
    end
  end

  def remove_from_session_cart
    item_id = params[:id].to_i
    session[:cart].reject! { |item| item['item_id'] == item_id.to_s }
    redirect_to cart_path, notice: 'Item removed from cart successfully.'
  end

  def calculate_total_price
    current_user.cart.cart_items.sum { |cart_item| cart_item.item.price * cart_item.quantity }
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
 
  def show
    if user_signed_in?
      @cart = current_user.cart || current_user.create_cart
      @cart_items = @cart.cart_items.includes(:item)
    else
      @cart_items =  session_cart_items 
    end
  end


  def session_cart_items
    session[:cart] ||= []
    item_ids = session[:cart].map { |item| item['item_id'].to_i }
    items = Item.where(id: item_ids).index_by(&:id) 
  
    session[:cart].map do |item|
      OpenStruct.new(
        item: items[item['item_id'].to_i], 
        quantity: item['quantity'].to_i
      )
    end
  end

  def remove_item
    if !user_signed_in?
      session[:cart] ||= []
      session[:cart].reject! { |i| i['item_id'] == params[:id].to_i }
      head :no_content
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    def show
        @Category = Category.find(params[:id])
        @item = @Category.items
      end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    if params[:search]
      @item = Item.where("LOWER(title) LIKE ?", "%#{params[(:search)].downcase}%")
    elsif params[:category_id]
      @category = Category.find(params[:category_id])
      @item =  @category.items
    else
      @item = Item.all
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :custom_authenticate_user!
  def index
    @orders = current_user.orders
  end

  def order_confirmation
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/layouts/_flash_message.html.erb
 <% flash.each do |key, message| %>
     <div class="text-danger alert d-flex justify-content-center"><%= message %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DinnerDash</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'https://code.jquery.com/jquery-3.6.0.min.js' %>
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
</head>
<body>
  <% if current_user&.admin? %>
    <%= render "shared/adminNav" %>
  <% else %>
    <%= render "shared/navbar" %>
  <% end %>
    <%= yield %>
</body>
</html>

app/views/shared/_adminNav.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'custom', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar">
        <a class="navbar-brand" href="#"><%= image_tag "logo.png" , class:"logo-image"%></a>
      </nav>
      
    <div class= "A">
      <div class="container">
         <ul class="navbar-nav">
            <li class="nav-item"><%= link_to 'Dashboard',root_path, class:"nav-link" %></li>
            <li class="nav-item"><%= link_to 'Manage Items', admin_items_path, class:"nav-link" %></li>
            <li class="nav-item"><%= link_to 'Manage Categories',admin_categories_path, class:"nav-link" %></li>
            <li class="nav-item"><%= link_to 'Manage Orders',admin_orders_path, class:"nav-link" %></li>
            <li class="nav-item"><%= link_to 'Sign Out', destroy_user_session_path, method: :delete , class:"nav-link"%></li>
        </ul>  
    </div>
  </div>
    </header>
  </body>
</html>






 

app/views/shared/_navbar.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'custom', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar">
        <a class="navbar-brand" href="#"><%= image_tag "logo.png" , class:"logo-image"%></a>
      </nav>
    <div class= "A">
      <div class="container">
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to 'Home', root_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'About Us', "#", class: 'nav-link' %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" role="button" data-toggle="dropdown">
              Categories
            </a>
            <div class="dropdown-menu table table-hover">
              <% @categories.each do |category| %>
                <%= image_tag "Food.jpeg", class:"category-image"%> <%= link_to category.name, items_path(category_id: category.id), class: 'dropdown-item' %>
              <% end %>
            </div>
          </li>
          <li class="nav-item">
            <%= link_to 'Contacts', "#", class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to cart_path, class: 'nav-link' do %>
              <i class="bi bi-cart4"></i>
              (<%= current_cart.cart_items.count %>)
            <% end %>
          </li>
          <li class="nav-item">
             <% if user_signed_in? %>
                <%= link_to "Sign Out", destroy_user_session_path,data: { no_turbolink: true }, method: :delete, class: 'nav-link' %>
             <% else %>
                <%= link_to "Sign In",new_user_session_path, class:"nav-link"%>
             <% end %>
          </li>
        <li class="nav-item">
        <div class="input-group">
          <div class="form-outline"> 
            <%= form_tag(items_path, method: :get, class: "form-inline") do %>
              <%= text_field_tag :search, params[:search], class: "form-control search-input", placeholder: "Search" %>
              <button type="submit" class="btn btn-dark fas fa-search search-button"></button>
            <% end %>
          </div>
        </div>
          </li>
        </ul>
    </div>
  </div>
    </header>
  </body>
</html>