config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :dashboards, only: [:index]
    resources :items
    resources :orders do
      member do
        get "paid_order"
        get "complete_order"
        get "cancel_order"
      end
    end
    resources :categories do
      member do
        post "remove_item"
      end
    end
  end
  resources :items, only: [:index]
  resource :cart, only: [:show]
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
  resources :categories, only: [:show]
  resources :orders, only: [:index]
  get 'order_confirmation', to: 'orders#order_confirmation'
  resources :cart_items, only: [:create, :destroy, :update] do
    collection do
      get 'checkout'
    end
  end
  root 'items#index'
end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :items
  has_one_attached :image
  validates :name, presence: true, uniqueness: true
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
    def index
        @categories = Category.all
    end

    def new
        @category = Category.new
    end

    def create
        @category = Category.new(category_params)
        if @category.save
          flash[:success] = "category successfully Added"
          redirect_to  admin_categories_path
        else
          flash[:error] = "Something went wrong"
          render 'new'
        end
    end

    def edit
        @category = Category.find(params[:id])
    end

    def update
        @category = Category.find(params[:id])
        if @category.update(category_params)
            redirect_to admin_categories_path, notice: 'category was successfully updated.'
        else
            render :edit
        end
    end

   def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to admin_categories_path
   end

   def remove_item 
    @category = Category.find(params[:id])
    item = Item.find(params[:item_id]) 
    @category.items.delete(item) 
    redirect_to edit_admin_category_path(@category) 
   end

   private

    def category_params
        params.require(:category).permit(:name,:image)
    end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    def show
        @Category = Category.find(params[:id])
        @item = @Category.items
      end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/edit.html.erb
<!DOCTYPE html>
<html>
<head>
    <%= stylesheet_link_tag 'items', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>
<body>
<div class="Box-container">
    <div class="row">
        <%= render "layouts/flash_message" %>
        <div class="Bx">
            <h2><b>Modify Category</b></h2>

            <%= form_with(model: [:admin, @category], url: admin_category_path(@category), method: :put, local: true) do |form| %>
                <div class="form-group">
                    <%= form.label :name %>
                </div>
                <%= form.text_field :name, class:"field" %>

                <%= form.submit "Submit", class:"Submit-button" %>
            <% end %>
                <br>
            -------------------------------------------------------------------------------------------------------------------
                <br>    
            <h2><B>Items in this Category<B></h2><br>
            <table class="table table-bordered">
                <thead class="thead-dark">
                    <tr>
                        <th class="n">Title</th>
                        <th class="n">Description</th>
                        <th class="n">Price</th>
                        <th class="n"></th>
                    </tr>
                </thead>
                <% @category.items.each do |item| %>
                    <tbody>
                        <tr>
                            <td><%= item.title %></td>
                            <td><%= item.description %></td>
                            <td><%= item.price %></td>
                            <td> <%= button_to 'Remove',remove_item_admin_category_path(@category, item_id: item.id), method: :post, class: "btn btn-danger", data: { confirm: 'Are you sure?' } %> </td>
                        </tr>
                <% end %>
            </table>
        </div>
    </div>
</div>

</body>
</html>

app/views/admin/categories/index.html.erb
<!DOCTYPE html>
<html lang = "en">
<head>
 <%= stylesheet_link_tag 'items', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>
<body>
<div class="Box-container">
    <%= render "layouts/flash_message" %>
    <table class="table1 c">
        <thead>
            <tr>
                <th class="n">Name</th>
                <th class="bu"><%= link_to new_admin_category_path, class: "btn btn-primary" do %><i class="fas fa-plus"></i><% end %></th>
            </tr>
        </thead>
        <% @categories.each do |category| %>
        <tbody>
            <tr>
                <td><%= image_tag "Food.jpeg", style:"width:20%;height:auto;border-radius:10px" %>  <%= category.name %></td>
                <td> 
                <%= button_to admin_category_path(category), method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure?' } do %><i class="fas fa-trash-alt"></i><% end %><br>
                <%= link_to edit_admin_category_path(category), class: "btn btn-dark" do %><i class="fas fa-edit"></i><% end %>
                </td>
            </tr>
        </tbody>
        <% end %>
    </table>
</div>                    
</body>
</html>




  

 

app/views/admin/categories/new.html.erb
<!DOCTYPE html>
<html>
<head>
    <%= stylesheet_link_tag 'items', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>
<body>
<div class="Box-container">
    <div class="row">
        <div class="Bx">
            <h2><b>Add Category</b></h2>

            <%= form_with(model: [:admin, @category], url: admin_categories_path, method: :post, local: true) do |form| %>
                <div class="form-group">
                    <%= form.label :name %>
                </div>
                <%= form.text_field :name, class:"field" %>

                <%= form.submit "Submit", class:"Submit-button" %>
            <% end %>
        </div>
    </div>
</div>

</body>
</html>